# Generated by Django 2.1.3 on 2019-02-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
