# Generated by Django 2.1.3 on 2019-02-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190220_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
