# Generated by Django 2.1.3 on 2019-02-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_variation_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='image',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
