# Generated by Django 2.1.3 on 2019-03-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190225_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystuff',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
