# Generated by Django 2.1.3 on 2019-11-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190314_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystuff',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companystuff',
            name='stuff',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variationtype',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variationtypeattribute',
            name='variation_type',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyStuff',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
        migrations.DeleteModel(
            name='VariationType',
        ),
        migrations.DeleteModel(
            name='VariationTypeAttribute',
        ),
    ]
