# Generated by Django 2.1.3 on 2019-11-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_phone_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='completed',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Phone Verified'), (2, 'Personal Info Passed'), (3, 'Store Info Passed')], default=0),
        ),
    ]
