# Generated by Django 2.1.3 on 2019-11-18 12:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0003_auto_20191118_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
    ]
