# Generated by Django 2.1.3 on 2019-11-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0004_auto_20191118_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='modified_on',
        ),
        migrations.AddField(
            model_name='product',
            name='dimension',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
