# Generated by Django 2.1.3 on 2019-11-25 17:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0005_auto_20191122_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None),
        ),
    ]
