# Generated by Django 2.1.3 on 2019-11-25 17:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0006_auto_20191125_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=8), size=8),
        ),
    ]
