# Generated by Django 2.1.3 on 2019-11-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=800)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
